version: '3.6'
services:
  socket-server1:
    image: "erdnando/coltrans-websocket-server:1.1"
    container_name: coltrans-web-socket-server
    restart: always
    ports:
      - "9001:8080"
    networks:
      coltrans_network:
       aliases:
        - socket-server1
  socket-server2:
    image: "erdnando/coltrans-websocket-server:1.1"
    container_name: coltrans-web-socket-server2
    restart: always
    ports:
      - "9002:8080"
    networks:
      coltrans_network:
       aliases:
        - socket-server2
  haproxy:
    image: "erdnando/coltrans-reverse-proxy-ha:1.0"
    container_name: coltrans-reverse-proxy-ha
    restart: always
    ports:
      - "81:81"
    networks:
      coltrans_network:
       aliases:
        - proxy-ha
  frontend-vue:
     image: "erdnando/coltrans-vuejs-websocket:1.0"
     container_name: coltrans-vuejs-websocket
     restart: always
     ports:
      - "8080:8080"
     environment:
       WEBSOCKET_SERVER: "http://192.168.0.6"
     networks:
      coltrans_network:
       aliases:
        - frontend
  frontend-vue2:
     image: "erdnando/coltrans-vuejs-websocket:1.0"
     container_name: coltrans-vuejs-websocket2
     restart: always
     ports:
      - "8081:8080"
     environment:
       WEBSOCKET_SERVER: "http://192.168.0.6"
     networks:
      coltrans_network:
       aliases:
        - frontend-2
  haproxy-frontend:
    image: "erdnando/coltrans-reverse-proxy-ha-frontend:1.0"
    container_name: coltrans-reverse-proxy-ha-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      coltrans_network:
       aliases:
        - proxy-ha-frontend
  rabbitmq:
    image: "rabbitmq:3.9-management"
    container_name: coltrans-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
       RABBITMQ_ERLANG_COOKIE: "cookie_for_clustering"
       RABBITMQ_DEFAULT_USER: "rabbit"
       RABBITMQ_DEFAULT_PASS: "password"
    volumes:
        - /mnt/0e74f96b-2899-46dc-b2b5-b0c41d7d9697/projectos/coltrans-solution/Bus/rabbitmq/data/:/var/lib/rabbitmq/
        - /mnt/0e74f96b-2899-46dc-b2b5-b0c41d7d9697/projectos/coltrans-solution/Bus/rabbitmq/log/:/var/log/rabbitmq
    networks:
      coltrans_network:
       aliases:
        - rabbitmq
  ms-incrementa:
    image: "erdnando/coltrans-ms-incrementa:1.0"
    container_name: coltrans-ms-incrementa
    restart: always
    ports:
      - "10001:8080"
    networks:
      coltrans_network:
       aliases:
        - ms-incrementa
  #jenkins:
  #  image: "jenkins/jenkins:lts"
  #  container_name: coltrans-jenkins
  #  restart: always
  #  ports:
  #    - "8083:8080"
  #    - "5000:5000"
  #  privileged: true
  #  user: root
  #  volumes:
  #    - ../CI_CD/jenkins_data:/var/jenkins_home
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  networks:
  #    coltrans_network:
  #     aliases:
  #      - jenkins <----
networks:
   coltrans_network:
    name: coltrans_network
    driver: bridge
    ipam:
      driver: default